services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    networks:
    - DemoMVC
networks:
  DemoMVC:
    driver: bridge