# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  demomvc:
    image: demomvc
    build:
      context: .
      dockerfile: DemoMVC/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5156:5156
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
