# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  demomvc:
    image: demomvc
    build:
      context: .
      dockerfile: DemoMVC/Dockerfile
    ports:
      - 5156:5156
    depends_on:
      - postgres
    networks:
      - DemoMVC
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    networks:
    - DemoMVC
networks:
  DemoMVC:
    driver: bridge